Pull Request
Hamst3R-23/Transaction pull request #1
Opened 2023-08-25 14:48 UTC by Hamst3R-23

2023-08-25 14:52 UTC, Hamst3R-23 commented
XVSADCSA

2023-08-25 14:59 UTC, Sparky775277 commented on README.md
> +
TMP

2023-08-25 15:00 UTC, Sparky775277 commented on README.md
> +
TMP

2023-08-25 15:00 UTC, Sparky775277 commented on README.md
> +
TMP

2023-08-25 20:36 UTC, O33ero requested changes

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +                body.getSenderAccountId(),
Зачем нужно разбирать входящий объект на кусочки. Это очень неудобно. Особенно когда первый и второй параметр это id-шники аккаунтов и порядок важен (первый - Sender, второй - Receiver). Перепутай местами и метод работает ровно в обратную сторону. Либо передавать объект полностью, либо создать другой объект (модель), который будет передаваться дальше в сервисы.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +        if (name == null) {
Лучше поставить default в `""` (пустую строку), чем проверять на `null`, поскольку легко таким образом получить NPE, что очень неприятно.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +    @GetMapping("/account")
Какой то стрём делать два метода, которые отличаются одной буквой. Если сильно не менять, то можно сделать это одним `/accounts`, который принимает `?name=aboba` или `?id=12`. И надо разделить на ситуации:
- Не передан ни `name`, ни `id` - вернуть всё
- Передан `name` - вернуть по имени
- Передан `id` - вернуть по id
- Передан и `name`, и `id` - вернуть по чему то одному, или получить по id и сравнить что имя совпадает

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +    @PostMapping("/set")
- Глагол в url-е - плохо, поскольку для глагола еще и надо объект и субъект, к которым этот глагол применяется, а в url-е такой информации нет;
- Можно это прочитать как `to set` - установить, а можно `set` - множество. Двойной смысл - плохо.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +        moneyService.addMoney(account.getId(), account.getAmount());
_В догонку к комменту про глаголы в url-е_.  В предыдущих url-ах глаголы были к аккаунтам (`setAccount`, `deleteAccount`), а тут уже к деньгам (`addMoney`, `subtractMoney`), хотя url вообще никак не поменялся.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +    public void subtractMoney(
Возвращать `void` для методов контроллера - плохая идея. Хотя бы `ResponseEntity<?>`, но вернуть что то нужно. Через `ResponseEntity<>` можно хотя бы вернуть Response Code.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +                .status(HttpStatus.OK)
Нигде не обрабатывается ситуация, что аккаунт может не найтись по id-шнику. В таких случаях надо возвращать `HttpStatus.NOT_FOUND`, сообщив пользователю, что он неправильно что-то указал.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +        return new ResponseEntity<List<Log>>(accountList, HttpStatus.OK);
Придирка: API должно быть последовательным. Если метод возвращает `Account`, то его тело будет иметь вид 
`
{
    "id" : "12",
    "name" : "boba",
    ....
}
`

А этот метод возвращает 
`
[
    {
        "log" : "A1",
        "time" : "20:12:00"
        ...
    },
    ...
]
`

Мелочь, но клиенты API точно за такое спасибо не скажут.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +        List<Log> accountList = logService.getAllAccounts(pageNum, pageSize, sortBy, orderQue, accountid);
Когда параметров >3, то уже сложно разобраться в порядке. По возможности такое надо объединять в объект `SortingPaginationSettings` (ну или как то так) и его передавать в сервис.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/exception/AccountNotFoundException.java
> +public class AccountNotFoundException extends RuntimeException{
Для всех `Exception`-ов считается хорошей практикой переопределять конструктор `RuntimeException(String message)`, чтобы можно было вместе с ошибкой передавать её контекст. 

Советую взглянуть на аннотацию `@ResponseStatus` и способ её применения с исключениями.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/httprequest/HttpRequest.java
> +            java.net.http.HttpRequest request = java.net.http.HttpRequest.newBuilder(new URI("http://www.cbr.ru/scripts/XML_daily.asp"))
Ссылку вынести в `application.properties`.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/httprequest/HttpRequest.java
> +            HttpClient client = HttpClient.newBuilder()
Наверное не стоит при каждом запросе создавать клиента, ведь можно создать его один раз, а потом переиспользовать сколько угодно.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/httprequest/HttpRequest.java
> +            throw new RuntimeException(e);
Не стоит:
1) Вполне конкретные исключения с описанием ошибок `URISyntexException`, `IOException`, `InterruptedException` "сужать" до обобщенного `RuntimeException` (даже передавая в него RuntimeException(_**e**_))
2) Выкидывать дефолтный `RuntimeException`. Нужно конкретизировать место и контекст ошибки, сделав новое исключение `RequestException` или что то такое.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/httprequest/HttpRequest.java
> +            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
Придирка: стоит посмотреть в сторону `WebFlux` и его `WebClient`. `WebClient` покрывает весь функционал `HttpClient`, плюс с верху добавляет кучу другого удобства, плюс вводит мир асинхронных запросов и реактивщины.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/parser/MyParser.java
> +public class MyParser {
Название класса не соответствует для серьезного промышленного проекта)

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/model/Account.java
> +    private long id;
Аккуратнее обращайтесь с `@Id` и его автоинкрементом. Лучше подцепить к нему Sequence из базы (короче, пусть инкрементом идшников записей занимается база, а не код).

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/parser/MyParser.java
> +            e.printStackTrace();
Ничего не отправляем в STDOUT. Для этого есть логгер, в него всё нужное и пишем.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/parser/MyParser.java
> +            parser.parse(http, handler);
`NPE`, если в предыдущем `try-catch` вылетело исключение. `parser` не создался, он `null`, а все равно к нему обращаются.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/parser/SaxParserHandler.java
> +    private final String TAG_CHAR_CODE = "CharCode";
Такие константы должны быть `private static final`

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/parser/SaxParserHandler.java
> +    boolean isValute = false;
`private boolean ...`

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/service/AccountService.java
> +        logRepository.insertLogInfo(account.getId(), "setAccount", amount, "New account created: name:" + name + " id:" + account.getId());
Если не удастся вставить лог по какой либо причине, то лог не создастся, а аккаунт сохранится. Не порядок. Нужно обернуть (сохранение аккаунта + лог) в транзакцию

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/service/ConversionService.java
> +        logRepository.insertLogInfo(id, "convertMoney", accountRepository.findById(id).get().getAmount(), account.getName() + " with id: " + id + " converted his amount to " + valute + " (" + account
Лучше воспользоваться `String.format(...)` вместо конкатенации. Невозможно понять в какаю строку в итоге соберутся данные.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/service/ConversionService.java
> +        account.setAmount(account.getAmount().divide(valuteAmount, 2, RoundingMode.HALF_UP));
2? HALF_UP? Почему? Нужно пояснение прям тут.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/service/AccountService.java
> +        logRepository.insertLogInfo(accountRepository.findAccountByName(name), "deleteAccount", null, "Delete account: name:" + name + " id:" + accountRepository.findAccountByName(name));
Вот эти `deleteAccount`, `setAccount` нужно вынести в enum.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/service/AccountService.java
> +        logRepository.insertLogInfo(accountRepository.findAccountByName(name), "deleteAccount", null, "Delete account: name:" + name + " id:" + accountRepository.findAccountByName(name));
`null`? Почему `null`? Можно обойтись без `null`, а то NPE и лишние проверки сами себе придумываем.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/service/ConversionService.java
> +        logRepository.insertLogInfo(id, "convertMoney", accountRepository.findById(id).get().getAmount(), account.getName() + " with id: " + id + " converted his amount to " + valute + " (" + account
Давай вот эти все вложенные вызовы - `accountRepository.findById()...`, `account.getAmount()` - на отдельных строках в отдельных переменных получим. Меньше кода - хорошо, но не в жертву читаемости.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/service/LogService.java
> +        Pageable paging = PageRequest.of(pageNo, pageSize, Sort.by(order));
Этот `sort` может вызывать кучу ошибок. Если передать в `Order()` не `desc` или `asc`, то все сломается. В `Sort.by()` можно передавать только определенные имена. От всего защитится невозможно, но нужно хотя бы в случае ошибки это отловить и нормально описать что произошло.

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/service/MoneyService.java
> +            if (newAccountAmount.compareTo(BigDecimal.valueOf(0)) < 0 || amount.compareTo(BigDecimal.valueOf(0)) < 0) {
Заменить `BigDecimal.valueOf(0)` на `BigDecimal.ZERO`

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/resources/schema.sql
> +    log varchar(100),
Придирка: маловато как то 100 символов. Лучше использовать `text` вместо `varchar(100)`

2023-08-25 20:36 UTC, O33ero commented on transaction/src/main/java/main/transaction/service/MoneyService.java
> +        if (accountRepository.checkAccount(id) && amount.compareTo(BigDecimal.valueOf(0)) >= 0) {
`>= 0` - Если условие не выполняется, то вылетает `AccountNotFoundException`. Как то исключение не описывает того что произошло. Скорее, даже запутывает.

2023-08-28 12:10 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +        if (name == null) {
done

2023-08-28 12:18 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +    @GetMapping("/account")
done

2023-08-28 12:41 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +    @PostMapping("/set")
done

2023-08-28 12:41 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +    public void subtractMoney(
done

2023-08-28 12:53 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +        List<Log> accountList = logService.getAllAccounts(pageNum, pageSize, sortBy, orderQue, accountid);
done

2023-08-28 13:19 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/httprequest/HttpRequest.java
> +            java.net.http.HttpRequest request = java.net.http.HttpRequest.newBuilder(new URI("http://www.cbr.ru/scripts/XML_daily.asp"))
done

2023-08-28 13:20 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/parser/MyParser.java
> +public class MyParser {
()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()

2023-08-28 13:32 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/parser/SaxParserHandler.java
> +    private final String TAG_CHAR_CODE = "CharCode";
done

2023-08-28 13:32 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/parser/SaxParserHandler.java
> +    boolean isValute = false;
done

2023-08-28 13:36 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/service/AccountService.java
> +        logRepository.insertLogInfo(account.getId(), "setAccount", amount, "New account created: name:" + name + " id:" + account.getId());
done

2023-08-28 13:46 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/service/AccountService.java
> +        logRepository.insertLogInfo(accountRepository.findAccountByName(name), "deleteAccount", null, "Delete account: name:" + name + " id:" + accountRepository.findAccountByName(name));
done

2023-08-28 14:08 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/service/LogService.java
> +        Pageable paging = PageRequest.of(pageNo, pageSize, Sort.by(order));
При вызове отличной от "asc", "desc" сортировки отдается "Bad Request"

2023-08-28 14:09 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/service/MoneyService.java
> +            if (newAccountAmount.compareTo(BigDecimal.valueOf(0)) < 0 || amount.compareTo(BigDecimal.valueOf(0)) < 0) {
done

2023-08-28 14:26 UTC, Hamst3R-23 commented on transaction/src/main/resources/schema.sql
> +    log varchar(100),
done

2023-08-28 15:00 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/service/ConversionService.java
> +        logRepository.insertLogInfo(id, "convertMoney", accountRepository.findById(id).get().getAmount(), account.getName() + " with id: " + id + " converted his amount to " + valute + " (" + account
done

2023-08-28 18:44 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/httprequest/HttpRequest.java
> +            HttpClient client = HttpClient.newBuilder()
Добавили HttpRequest в контекст, в сервисе ConversionService его вытаскиваем

2023-08-28 18:57 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/service/ConversionService.java
> +        logRepository.insertLogInfo(id, "convertMoney", accountRepository.findById(id).get().getAmount(), account.getName() + " with id: " + id + " converted his amount to " + valute + " (" + account
Создан новый метод в AccountRepository, замещающий accountRepository.findById(id).get().getAmount()

2023-08-29 15:25 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +                .status(HttpStatus.OK)
done

2023-08-29 15:25 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/exception/AccountNotFoundException.java
> +public class AccountNotFoundException extends RuntimeException{
done

2023-08-29 15:26 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/httprequest/HttpRequest.java
> +            throw new RuntimeException(e);
done

2023-08-29 15:26 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/parser/MyParser.java
> +            e.printStackTrace();
done

2023-08-29 15:26 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/parser/MyParser.java
> +            parser.parse(http, handler);
done

2023-08-29 15:26 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/service/MoneyService.java
> +        if (accountRepository.checkAccount(id) && amount.compareTo(BigDecimal.valueOf(0)) >= 0) {
done

2023-08-29 16:36 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +        moneyService.addMoney(account.getId(), account.getAmount());
done

2023-08-29 16:37 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/httprequest/HttpRequest.java
> +            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
()

2023-08-29 16:39 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/service/ConversionService.java
> +        account.setAmount(account.getAmount().divide(valuteAmount, 2, RoundingMode.HALF_UP));
(https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/RoundingMode.html)
Изменили на HALF_EVEN

2023-08-29 16:43 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/controller/AccountController.java
> +        return new ResponseEntity<List<Log>>(accountList, HttpStatus.OK);
done

2023-08-29 16:46 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/model/Account.java
> +    private long id;
Hibernate ()()()()()()()()()()() ?!?!?!!?!?

2023-08-29 19:58 UTC, Hamst3R-23 commented on transaction/src/main/java/main/transaction/service/AccountService.java
> +        logRepository.insertLogInfo(accountRepository.findAccountByName(name), "deleteAccount", null, "Delete account: name:" + name + " id:" + accountRepository.findAccountByName(name));
done

2023-08-29 20:33 UTC, closed without merging